secure/updatePlace added
satlantis-dev/api-client pull request #31
Opened 2024-08-18 02:56 UTC by Devang47

2024-08-18 03:51 UTC, BlowaterNostr requested changes
@Devang47 Thanks for submitting the first PR. Well done. This codebase is the bridge between the client and the backend. Therefore, please add an intergration test. Look at `tests` dir for examples.

2024-08-19 16:01 UTC, alberlantis requested changes
@Devang47 Please remember to `rebase` as well

2024-08-19 16:01 UTC, alberlantis commented on tests/authed_api.test.ts
> +});
A good way to test an `update` function is to
1. get a place 
2. update this place's name to some random data
3. get it again, verify it is changed to this random data
4. set it back
5. get it again and verify it is back to the original data

2024-08-19 17:11 UTC, Devang47 commented on tests/authed_api.test.ts
> +});
Done

2024-08-20 04:57 UTC, merged